
import { Destination, Region, Category, BlogPost } from './types';

export const DESTINATIONS: Destination[] = [
  {
    id: 1,
    name: "New York City",
    state: "New York",
    stateCode: "NY",
    region: Region.NORTHEAST,
    category: Category.CITY,
    description: "The city that never sleeps, offering iconic landmarks, world-class museums, and vibrant culture.",
    longDescription: "New York City comprises 5 boroughs sitting where the Hudson River meets the Atlantic Ocean. At its core is Manhattan, a densely populated borough that’s among the world’s major commercial, financial and cultural centers. Its iconic sites include skyscrapers such as the Empire State Building and sprawling Central Park.",
    imageUrl: "https://picsum.photos/seed/nyc/800/600",
    bestTimeToVisit: "September to October",
    activities: ["Visit Times Square", "See a Broadway Show", "Explore Central Park", "Statue of Liberty"],
    rating: 4.8,
  },
  {
    id: 2,
    name: "Yosemite National Park",
    state: "California",
    stateCode: "CA",
    region: Region.WEST,
    category: Category.NATIONAL_PARK,
    description: "A breathtaking landscape of towering granite cliffs, giant sequoia groves, and stunning waterfalls.",
    longDescription: "Yosemite National Park is in California’s Sierra Nevada mountains. It’s famed for its giant, ancient sequoia trees, and for Tunnel View, the iconic vista of towering Bridalveil Fall and the granite cliffs of El Capitan and Half Dome. In Yosemite Village are shops, restaurants, lodging, the Yosemite Museum and the Ansel Adams Gallery.",
    imageUrl: "https://picsum.photos/seed/yosemite/800/600",
    bestTimeToVisit: "May and September",
    activities: ["Hike to Vernal Fall", "Drive Tioga Road", "See El Capitan", "Visit Mariposa Grove"],
    rating: 4.9,
  },
  {
    id: 3,
    name: "New Orleans",
    state: "Louisiana",
    stateCode: "LA",
    region: Region.SOUTHEAST,
    category: Category.CITY,
    description: "A melting pot of French, African and American cultures, famous for its music, food, and festivals.",
    longDescription: "New Orleans is a Louisiana city on the Mississippi River, near the Gulf of Mexico. Nicknamed the 'Big Easy,' it's known for its round-the-clock nightlife, vibrant live-music scene and spicy, singular cuisine reflecting its history as a melting pot of French, African and American cultures. Embodying its festive spirit is Mardi Gras, the late-winter carnival famed for raucous costumed parades and street parties.",
    imageUrl: "https://picsum.photos/seed/nola/800/600",
    bestTimeToVisit: "February to May",
    activities: ["Explore the French Quarter", "Listen to Jazz on Frenchmen Street", "Eat Beignets", "Take a Steamboat Cruise"],
    rating: 4.6,
  },
  {
    id: 4,
    name: "Grand Canyon",
    state: "Arizona",
    stateCode: "AZ",
    region: Region.SOUTHWEST,
    category: Category.NATIONAL_PARK,
    description: "A massive, awe-inspiring canyon carved by the Colorado River, offering dramatic vistas.",
    longDescription: "The Grand Canyon in Arizona is a natural formation distinguished by layered bands of red rock, revealing millions of years of geological history in cross-section. Vast in scale, the canyon averages about 10 miles across and a mile deep along its 277-mile length. Much of the area is a national park, with Colorado River white-water rapids and sweeping vistas.",
    imageUrl: "https://picsum.photos/seed/grandcanyon/800/600",
    bestTimeToVisit: "March to May & September to November",
    activities: ["Hike the Bright Angel Trail", "Watch sunrise at Mather Point", "Visit the North Rim", "Raft the Colorado River"],
    rating: 4.9,
  },
  {
    id: 5,
    name: "Chicago",
    state: "Illinois",
    stateCode: "IL",
    region: Region.MIDWEST,
    category: Category.CITY,
    description: "Known for its bold architecture, impressive skyline, and world-class museums.",
    longDescription: "Chicago, on Lake Michigan in Illinois, is among the largest cities in the U.S. Famed for its bold architecture, it has a skyline punctuated by skyscrapers such as the iconic John Hancock Center, 1,451-ft. Willis Tower (formerly the Sears Tower) and the neo-Gothic Tribune Tower. The city is also renowned for its museums, including the Art Institute of Chicago with its noted Impressionist and Post-Impressionist works.",
    imageUrl: "https://picsum.photos/seed/chicago/800/600",
    bestTimeToVisit: "April to May & September to October",
    activities: ["Visit Millennium Park", "Go up Willis Tower", "Explore Navy Pier", "Take an architectural boat tour"],
    rating: 4.7,
  },
  {
    id: 6,
    name: "Boston",
    state: "Massachusetts",
    stateCode: "MA",
    region: Region.NORTHEAST,
    category: Category.HISTORICAL,
    description: "A city steeped in American history, with charming neighborhoods and a revolutionary past.",
    longDescription: "Boston is Massachusetts’ capital and largest city. Founded in 1630, it’s one of the oldest cities in the U.S. The key role it played in the American Revolution is highlighted on the Freedom Trail, a 2.5-mile walking route of historic sites that tells the story of the nation’s founding. One of its stops, former meeting house Faneuil Hall, is a popular marketplace.",
    imageUrl: "https://picsum.photos/seed/boston/800/600",
    bestTimeToVisit: "June to October",
    activities: ["Walk the Freedom Trail", "Visit Fenway Park", "Explore the North End", "Tour Harvard University"],
    rating: 4.7,
  },
  {
    id: 7,
    name: "Miami",
    state: "Florida",
    stateCode: "FL",
    region: Region.SOUTHEAST,
    category: Category.COASTAL,
    description: "Famous for its vibrant nightlife, beautiful beaches, and Art Deco architecture.",
    longDescription: "Miami is an international city at Florida's southeastern tip. Its Cuban influence is reflected in the cafes and cigar shops that line Calle Ocho in Little Havana. On barrier islands across the turquoise waters of Biscayne Bay is Miami Beach, home to South Beach. This glamorous neighborhood is famed for its colorful art deco buildings, white sand, surfside hotels and trendsetting nightclubs.",
    imageUrl: "https://picsum.photos/seed/miami/800/600",
    bestTimeToVisit: "December to May",
    activities: ["Relax on South Beach", "Explore the Art Deco Historic District", "Visit Little Havana", "Experience the nightlife"],
    rating: 4.5,
  },
   {
    id: 8,
    name: "Zion National Park",
    state: "Utah",
    stateCode: "UT",
    region: Region.SOUTHWEST,
    category: Category.NATIONAL_PARK,
    description: "Features massive sandstone cliffs of cream, pink, and red that soar into a brilliant blue sky.",
    longDescription: "Zion National Park is a southwest Utah nature preserve distinguished by Zion Canyon’s steep red cliffs. Zion Canyon Scenic Drive cuts through its main section, leading to forest trails along the Virgin River. The river flows to the Emerald Pools, which have waterfalls and a hanging garden. Also along the river, partly through deep chasms, is Zion Narrows, a popular canyoneering spot.",
    imageUrl: "https://picsum.photos/seed/zion/800/600",
    bestTimeToVisit: "April to May & September to October",
    activities: ["Hike The Narrows", "Climb Angels Landing", "Drive the Zion-Mount Carmel Highway", "Canyoneering"],
    rating: 4.9,
  },
  {
    id: 9,
    name: "Seattle",
    state: "Washington",
    stateCode: "WA",
    region: Region.WEST,
    category: Category.CITY,
    description: "Home of the iconic Space Needle, a thriving tech industry, and vibrant music scene.",
    longDescription: "Seattle, a city on Puget Sound in the Pacific Northwest, is surrounded by water, mountains and evergreen forests, and contains thousands of acres of parkland. Washington State’s largest city, it’s home to a large tech industry, with Microsoft and Amazon headquartered in its metropolitan area. The futuristic Space Needle, a 1962 World’s Fair legacy, is its most iconic landmark.",
    imageUrl: "https://picsum.photos/seed/seattle/800/600",
    bestTimeToVisit: "July and August",
    activities: ["Visit the Space Needle", "Explore Pike Place Market", "Tour the Museum of Pop Culture", "Take a ferry ride"],
    rating: 4.6,
  },
  {
    id: 10,
    name: "Charleston",
    state: "South Carolina",
    stateCode: "SC",
    region: Region.SOUTHEAST,
    category: Category.HISTORICAL,
    description: "A historic port city defined by cobblestone streets, horse-drawn carriages and pastel antebellum houses.",
    longDescription: "Charleston, the South Carolina port city founded in 1670, is defined by its cobblestone streets, horse-drawn carriages and pastel antebellum houses, particularly in the elegant French Quarter and Battery districts. The Battery promenade and Waterfront Park both overlook Charleston Harbor, while Fort Sumter, a federal monument where the first shots of the Civil War were fired, lies across the water.",
    imageUrl: "https://picsum.photos/seed/charleston/800/600",
    bestTimeToVisit: "March to May",
    activities: ["Explore the Historic District", "Visit Rainbow Row", "Tour Fort Sumter", "Relax at Folly Beach"],
    rating: 4.8,
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 1,
    title: "Top 5 National Parks to Visit in the Fall",
    excerpt: "Autumn brings a spectacular display of colors to America's national parks. Discover the best spots to witness the beauty of the season.",
    author: "Alex Johnson",
    date: "October 15, 2023",
    tags: ["National Parks", "Fall", "Travel Guide"],
    imageUrl: "https://picsum.photos/seed/blog1/400/300",
  },
  {
    id: 2,
    title: "A Foodie's Guide to New Orleans",
    excerpt: "From beignets to gumbo, explore the culinary delights that make New Orleans a top destination for food lovers.",
    author: "Maria Garcia",
    date: "September 28, 2023",
    tags: ["Food", "City", "New Orleans"],
    imageUrl: "https://picsum.photos/seed/blog2/400/300",
  },
  {
    id: 3,
    title: "Planning Your First Trip to New York City",
    excerpt: "The Big Apple can be overwhelming. Here are our essential tips for first-time visitors to make the most of their trip.",
    author: "Sam Lee",
    date: "September 5, 2023",
    tags: ["City Guide", "Tips", "NYC"],
    imageUrl: "https://picsum.photos/seed/blog3/400/300",
  },
];
